// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddPersonaReq struct {
	Name   string `json:"name"`
	Prompt string `json:"prompt"`
}

type AppendStateReq struct {
	GroupId int64 `json:"group_id"`
	UserId  int64 `json:"user_id"`
	StateId int64 `json:"state_id"`
}

type CreateGroupReq struct {
	Name string `json:"name"`
}

type CreateStateReq struct {
	GroupId int64  `json:"group_id"`
	Name    string `json:"name"`
	Prompt  string `json:"prompt"`
}

type DelPersonaReq struct {
	Id int64 `json:"id"`
}

type EditPersonaReq struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Prompt string `json:"prompt"`
}

type GetGroupMembersReq struct {
	Id int64 `json:"id"`
}

type GetGroupMembersResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type GetPersonaReq struct {
	Name string `json:"name"`
}

type GetPersonaResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Prompt string `json:"prompt"`
}

type GetStateByGroupReq struct {
	GroupId int64 `json:"group_id"`
}

type GetStateFromUser struct {
	GroupId int64
}

type GetStateResp struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Prompt     string `json:"prompt"`
	AssignedBy int64  `json:"assigned_by"`
}

type GetUserInfoReq struct {
	Id int64 `json:"id"`
}

type GetUserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type GetUserStateByGroupReq struct {
	GroupId int64 `json:"group_id"`
	UserId  int64 `json:"user_id"`
}

type GetUserStateResp struct {
	Id     int64  `json:"id"`
	UserId int64  `json:"user_id"`
	Name   string `json:"name"`
}

type JoinGroupReq struct {
	Id int64 `json:"id"`
}

type LeaveGroupReq struct {
	Id int64 `json:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type RemoveStateReq struct {
	GroupId int64 `json:"group_id"`
	UserId  int64 `json:"user_id"`
	StateId int64 `json:"state_id"`
}

type WsReq struct {
	Token string `form:"token"`
}
