// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	group "ginchat2/internal/handler/group"
	persona "ginchat2/internal/handler/persona"
	state "ginchat2/internal/handler/state"
	"ginchat2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: infoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: wsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/join",
				Handler: group.JoinGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/leave",
				Handler: group.LeaveGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/members",
				Handler: group.GetGroupMembersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/persona/add",
				Handler: persona.AddPersonaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/persona/all",
				Handler: persona.GetAllPersonaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/persona/del",
				Handler: persona.DelPersonaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/persona/edit",
				Handler: persona.EditPersonaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/persona/get",
				Handler: persona.GetPersonaHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/state/append",
				Handler: state.AppendStateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/state/create",
				Handler: state.CreateStateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/state/group",
				Handler: state.GetStateByGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/state/group/all",
				Handler: state.GetAllStateByGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/state/group/user",
				Handler: state.GetUserStateByGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/state/remove",
				Handler: state.RemoveStateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
