// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{}, true)
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicGroupsIdPrefix   = "cache:public:groups:id:"
	cachePublicGroupsNamePrefix = "cache:public:groups:name:"
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groups, error)
		FindOneByName(ctx context.Context, name string) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupsModel struct {
		sqlc.CachedConn
		table string
	}

	Groups struct {
		Id        int64     `db:"id"`         // 主键ID
		Name      string    `db:"name"`       // 群组名称（唯一）
		CreatorId int64     `db:"creator_id"` // 创建者用户ID
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newGroupsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupsModel {
	return &defaultGroupsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."groups"`,
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicGroupsIdKey := fmt.Sprintf("%s%v", cachePublicGroupsIdPrefix, id)
	publicGroupsNameKey := fmt.Sprintf("%s%v", cachePublicGroupsNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicGroupsIdKey, publicGroupsNameKey)
	return err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id int64) (*Groups, error) {
	publicGroupsIdKey := fmt.Sprintf("%s%v", cachePublicGroupsIdPrefix, id)
	var resp Groups
	err := m.QueryRowCtx(ctx, &resp, publicGroupsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) FindOneByName(ctx context.Context, name string) (*Groups, error) {
	publicGroupsNameKey := fmt.Sprintf("%s%v", cachePublicGroupsNamePrefix, name)
	var resp Groups
	err := m.QueryRowIndexCtx(ctx, &resp, publicGroupsNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where name = $1 limit 1", groupsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	publicGroupsIdKey := fmt.Sprintf("%s%v", cachePublicGroupsIdPrefix, data.Id)
	publicGroupsNameKey := fmt.Sprintf("%s%v", cachePublicGroupsNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, groupsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.CreatorId)
	}, publicGroupsIdKey, publicGroupsNameKey)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, newData *Groups) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicGroupsIdKey := fmt.Sprintf("%s%v", cachePublicGroupsIdPrefix, data.Id)
	publicGroupsNameKey := fmt.Sprintf("%s%v", cachePublicGroupsNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.CreatorId)
	}, publicGroupsIdKey, publicGroupsNameKey)
	return err
}

func (m *defaultGroupsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicGroupsIdPrefix, primary)
}

func (m *defaultGroupsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
