// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{}, true)
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	messageRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(messageFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicMessageIdPrefix = "cache:public:message:id:"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Message, error)
		Update(ctx context.Context, data *Message) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMessageModel struct {
		sqlc.CachedConn
		table string
	}

	Message struct {
		Id          int64          `db:"id"`           // id
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		DeletedAt   sql.NullInt64  `db:"deleted_at"`   // 删除时间戳
		FromUserId  sql.NullInt64  `db:"from_user_id"` // 发送人ID
		ToUserId    sql.NullInt64  `db:"to_user_id"`   // 发送对象ID
		Content     string         `db:"content"`      // 消息内容
		Url         string         `db:"url"`          // 文件或者图片地址
		Pic         sql.NullString `db:"pic"`          // 缩略图
		MessageType sql.NullInt64  `db:"message_type"` // 消息类型：1单聊，2群聊
		ContentType sql.NullInt64  `db:"content_type"` // 消息内容类型：1文字，2语音，3视频
	}
)

func newMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageModel {
	return &defaultMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."message"`,
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, id int64) error {
	publicMessageIdKey := fmt.Sprintf("%s%v", cachePublicMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicMessageIdKey)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id int64) (*Message, error) {
	publicMessageIdKey := fmt.Sprintf("%s%v", cachePublicMessageIdPrefix, id)
	var resp Message
	err := m.QueryRowCtx(ctx, &resp, publicMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", messageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	publicMessageIdKey := fmt.Sprintf("%s%v", cachePublicMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, messageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.FromUserId, data.ToUserId, data.Content, data.Url, data.Pic, data.MessageType, data.ContentType)
	}, publicMessageIdKey)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	publicMessageIdKey := fmt.Sprintf("%s%v", cachePublicMessageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, messageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.DeletedAt, data.FromUserId, data.ToUserId, data.Content, data.Url, data.Pic, data.MessageType, data.ContentType)
	}, publicMessageIdKey)
	return err
}

func (m *defaultMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicMessageIdPrefix, primary)
}

func (m *defaultMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", messageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
