// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	personaFieldNames          = builder.RawFieldNames(&Persona{}, true)
	personaRows                = strings.Join(personaFieldNames, ",")
	personaRowsExpectAutoSet   = strings.Join(stringx.Remove(personaFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	personaRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(personaFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicPersonaIdPrefix = "cache:public:persona:id:"
)

type (
	personaModel interface {
		Insert(ctx context.Context, data *Persona) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Persona, error)
		Update(ctx context.Context, data *Persona) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPersonaModel struct {
		sqlc.CachedConn
		table string
	}

	Persona struct {
		Id        int64     `db:"id"`         // 主键ID
		UserId    int64     `db:"user_id"`    // 用户ID，关联用户表
		Name      string    `db:"name"`       // 角色名称
		Prompt    string    `db:"prompt"`     // 角色设定提示词
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newPersonaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPersonaModel {
	return &defaultPersonaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."persona"`,
	}
}

func (m *defaultPersonaModel) Delete(ctx context.Context, id int64) error {
	publicPersonaIdKey := fmt.Sprintf("%s%v", cachePublicPersonaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicPersonaIdKey)
	return err
}

func (m *defaultPersonaModel) FindOne(ctx context.Context, id int64) (*Persona, error) {
	publicPersonaIdKey := fmt.Sprintf("%s%v", cachePublicPersonaIdPrefix, id)
	var resp Persona
	err := m.QueryRowCtx(ctx, &resp, publicPersonaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", personaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPersonaModel) Insert(ctx context.Context, data *Persona) (sql.Result, error) {
	publicPersonaIdKey := fmt.Sprintf("%s%v", cachePublicPersonaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, personaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Prompt)
	}, publicPersonaIdKey)
	return ret, err
}

func (m *defaultPersonaModel) Update(ctx context.Context, data *Persona) error {
	publicPersonaIdKey := fmt.Sprintf("%s%v", cachePublicPersonaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, personaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Name, data.Prompt)
	}, publicPersonaIdKey)
	return err
}

func (m *defaultPersonaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicPersonaIdPrefix, primary)
}

func (m *defaultPersonaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", personaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPersonaModel) tableName() string {
	return m.table
}
