// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stateFieldNames          = builder.RawFieldNames(&State{}, true)
	stateRows                = strings.Join(stateFieldNames, ",")
	stateRowsExpectAutoSet   = strings.Join(stringx.Remove(stateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	stateRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(stateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicStateIdPrefix          = "cache:public:state:id:"
	cachePublicStateGroupIdNamePrefix = "cache:public:state:groupId:name:"
)

type (
	stateModel interface {
		Insert(ctx context.Context, data *State) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*State, error)
		FindOneByGroupIdName(ctx context.Context, groupId int64, name string) (*State, error)
		Update(ctx context.Context, data *State) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStateModel struct {
		sqlc.CachedConn
		table string
	}

	State struct {
		Id        int64     `db:"id"`         // 主键ID
		GroupId   int64     `db:"group_id"`   // 所属群组ID
		Name      string    `db:"name"`       // 状态名称（同一群组内唯一）
		CreatorId int64     `db:"creator_id"` // 创建者用户ID
		Prompt    string    `db:"prompt"`     // 状态作用提示词
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newStateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStateModel {
	return &defaultStateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."state"`,
	}
}

func (m *defaultStateModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicStateGroupIdNameKey := fmt.Sprintf("%s%v:%v", cachePublicStateGroupIdNamePrefix, data.GroupId, data.Name)
	publicStateIdKey := fmt.Sprintf("%s%v", cachePublicStateIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicStateGroupIdNameKey, publicStateIdKey)
	return err
}

func (m *defaultStateModel) FindOne(ctx context.Context, id int64) (*State, error) {
	publicStateIdKey := fmt.Sprintf("%s%v", cachePublicStateIdPrefix, id)
	var resp State
	err := m.QueryRowCtx(ctx, &resp, publicStateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", stateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStateModel) FindOneByGroupIdName(ctx context.Context, groupId int64, name string) (*State, error) {
	publicStateGroupIdNameKey := fmt.Sprintf("%s%v:%v", cachePublicStateGroupIdNamePrefix, groupId, name)
	var resp State
	err := m.QueryRowIndexCtx(ctx, &resp, publicStateGroupIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where group_id = $1 and name = $2 limit 1", stateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStateModel) Insert(ctx context.Context, data *State) (sql.Result, error) {
	publicStateGroupIdNameKey := fmt.Sprintf("%s%v:%v", cachePublicStateGroupIdNamePrefix, data.GroupId, data.Name)
	publicStateIdKey := fmt.Sprintf("%s%v", cachePublicStateIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, stateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.Name, data.CreatorId, data.Prompt)
	}, publicStateGroupIdNameKey, publicStateIdKey)
	return ret, err
}

func (m *defaultStateModel) Update(ctx context.Context, newData *State) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicStateGroupIdNameKey := fmt.Sprintf("%s%v:%v", cachePublicStateGroupIdNamePrefix, data.GroupId, data.Name)
	publicStateIdKey := fmt.Sprintf("%s%v", cachePublicStateIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, stateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.GroupId, newData.Name, newData.CreatorId, newData.Prompt)
	}, publicStateGroupIdNameKey, publicStateIdKey)
	return err
}

func (m *defaultStateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicStateIdPrefix, primary)
}

func (m *defaultStateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", stateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStateModel) tableName() string {
	return m.table
}
