// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userGroupStateFieldNames          = builder.RawFieldNames(&UserGroupState{}, true)
	userGroupStateRows                = strings.Join(userGroupStateFieldNames, ",")
	userGroupStateRowsExpectAutoSet   = strings.Join(stringx.Remove(userGroupStateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userGroupStateRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userGroupStateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserGroupStateIdPrefix                   = "cache:public:userGroupState:id:"
	cachePublicUserGroupStateUserIdGroupIdStateIdPrefix = "cache:public:userGroupState:userId:groupId:stateId:"
)

type (
	userGroupStateModel interface {
		Insert(ctx context.Context, data *UserGroupState) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserGroupState, error)
		FindOneByUserIdGroupIdStateId(ctx context.Context, userId int64, groupId int64, stateId int64) (*UserGroupState, error)
		Update(ctx context.Context, data *UserGroupState) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserGroupStateModel struct {
		sqlc.CachedConn
		table string
	}

	UserGroupState struct {
		Id         int64     `db:"id"`          // 主键ID
		UserId     int64     `db:"user_id"`     // 用户ID
		GroupId    int64     `db:"group_id"`    // 群组ID
		StateId    int64     `db:"state_id"`    // 状态ID
		AssignedBy int64     `db:"assigned_by"` // 由谁附加该状态
		ExpiresAt  time.Time `db:"expires_at"`  // 状态过期时间（NULL表示永不过期）
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newUserGroupStateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserGroupStateModel {
	return &defaultUserGroupStateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_group_state"`,
	}
}

func (m *defaultUserGroupStateModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicUserGroupStateIdKey := fmt.Sprintf("%s%v", cachePublicUserGroupStateIdPrefix, id)
	publicUserGroupStateUserIdGroupIdStateIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserGroupStateUserIdGroupIdStateIdPrefix, data.UserId, data.GroupId, data.StateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicUserGroupStateIdKey, publicUserGroupStateUserIdGroupIdStateIdKey)
	return err
}

func (m *defaultUserGroupStateModel) FindOne(ctx context.Context, id int64) (*UserGroupState, error) {
	publicUserGroupStateIdKey := fmt.Sprintf("%s%v", cachePublicUserGroupStateIdPrefix, id)
	var resp UserGroupState
	err := m.QueryRowCtx(ctx, &resp, publicUserGroupStateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userGroupStateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserGroupStateModel) FindOneByUserIdGroupIdStateId(ctx context.Context, userId int64, groupId int64, stateId int64) (*UserGroupState, error) {
	publicUserGroupStateUserIdGroupIdStateIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserGroupStateUserIdGroupIdStateIdPrefix, userId, groupId, stateId)
	var resp UserGroupState
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserGroupStateUserIdGroupIdStateIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where user_id = $1 and group_id = $2 and state_id = $3 limit 1", userGroupStateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, groupId, stateId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserGroupStateModel) Insert(ctx context.Context, data *UserGroupState) (sql.Result, error) {
	publicUserGroupStateIdKey := fmt.Sprintf("%s%v", cachePublicUserGroupStateIdPrefix, data.Id)
	publicUserGroupStateUserIdGroupIdStateIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserGroupStateUserIdGroupIdStateIdPrefix, data.UserId, data.GroupId, data.StateId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, userGroupStateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.GroupId, data.StateId, data.AssignedBy, data.ExpiresAt)
	}, publicUserGroupStateIdKey, publicUserGroupStateUserIdGroupIdStateIdKey)
	return ret, err
}

func (m *defaultUserGroupStateModel) Update(ctx context.Context, newData *UserGroupState) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicUserGroupStateIdKey := fmt.Sprintf("%s%v", cachePublicUserGroupStateIdPrefix, data.Id)
	publicUserGroupStateUserIdGroupIdStateIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicUserGroupStateUserIdGroupIdStateIdPrefix, data.UserId, data.GroupId, data.StateId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, userGroupStateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.GroupId, newData.StateId, newData.AssignedBy, newData.ExpiresAt)
	}, publicUserGroupStateIdKey, publicUserGroupStateUserIdGroupIdStateIdKey)
	return err
}

func (m *defaultUserGroupStateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserGroupStateIdPrefix, primary)
}

func (m *defaultUserGroupStateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userGroupStateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserGroupStateModel) tableName() string {
	return m.table
}
